#!/usr/bin/env python3
"""Build chat-style SFT data with REAL inference-time prompts and tool schemas.

Differences from build_agent_sft.py:
  1. System prompts come directly from agent/flow/instructions.py (not condensed).
  2. Tool schemas loaded from training/runtime_schemas.json (real MCP + handoff
     schemas, generated by extract_runtime_schemas.py).
  3. transfer_to_operator `targets` argument is a list of strings (matches what
     the OpenAI Agents SDK expects from _OperatorHandoffPayload).
  4. Stratified train/test split by (category × scenario) pair.

PRE-REQUISITES:
    Run extract_runtime_schemas.py FIRST (with MCP server up).

Usage (on pod):
    cd slurm-agent
    python training/extract_runtime_schemas.py            # produces runtime_schemas.json
    python training/build_agent_sft_v2.py --split 0.2     # 80/20 stratified split
    # → training/out/agent_sft_v2.jsonl + agent_sft_v2_test.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Import REAL inference prompts (these are what the live agent uses)
from agent.flow.instructions import _OBSERVER_BASE, _OPERATOR_BASE  # type: ignore

# Reuse simulator + helper functions from v1
from training.build_agent_sft import (  # type: ignore
    _build_tool_args as _v1_build_tool_args,
    _simulate_tool_output,
    _build_final_response,
    DANGEROUS_TOOLS,
    OBSERVER_TOOL_NAMES,
    OPERATOR_TOOL_NAMES,
)


def _build_tool_args(tool_name: str, row: dict) -> dict:
    """Wrap v1 with corrections so emitted args match the REAL MCP signatures.

    Critical fixes:
      - scontrol_update: real sig is (entity, id, params). v1 emits {job_id, updates}.
      - scancel: real sig is (job_id, user). v1 may emit {partition} or {state}
        which the tool will reject. Fall back to job_id from source_state when
        no explicit job_id can be inferred.
      - scontrol_node: keep (node, state, reason). v1 lower-cases state; MCP
        accepts case-insensitive but training data should mirror inference
        usage which lowercases.
      - sbatch: ensure flags is present (real sig is (script, flags)).
    """
    user_input = row.get("input", "")
    jobs = row.get("source_state", {}).get("jobs", {})
    job_ids = re.findall(r"\b(\d{4,5})\b", user_input)

    if tool_name == "scontrol_update":
        jid = job_ids[0] if job_ids else (list(jobs.keys())[0] if jobs else "1001")
        # Choose params from intent
        if "time" in user_input.lower() or "limit" in user_input.lower():
            params = "TimeLimit=12:00:00"
        elif "qos" in user_input.lower():
            params = "QOS=normal"
        elif "partition" in user_input.lower():
            params = "Partition=normal"
        else:
            params = "TimeLimit=12:00:00"
        return {"entity": "job", "id": jid, "params": params}

    if tool_name == "scancel":
        if job_ids:
            return {"job_id": ",".join(job_ids[:3])}
        # Discovery scope: in operator half we run squeue first then scancel
        # with the resolved IDs from source_state.
        candidate_ids = []
        for j, info in (jobs or {}).items():
            if info.get("state") in {"RUNNING", "PENDING"}:
                candidate_ids.append(str(j))
            if len(candidate_ids) >= 3:
                break
        if candidate_ids:
            return {"job_id": ",".join(candidate_ids)}
        return {"job_id": "1001"}

    if tool_name == "sbatch":
        script_match = re.search(r"(\S+\.sh)", user_input)
        flags = ""
        ui_low = user_input.lower()
        if "gpu" in ui_low:
            flags = "--partition=gpu --gres=gpu:1"
        elif "high" in ui_low and "memory" in ui_low:
            flags = "--mem=64G"
        return {"script": script_match.group(1) if script_match else "train.sh", "flags": flags}

    # Fallback: delegate to v1 for everything else
    return _v1_build_tool_args(tool_name, row)


def _validate_args_against_schema(tool_name: str, args: dict, all_schemas: dict) -> bool:
    """Return True iff `args` satisfies the schema's required fields and contains
    only properties allowed by the schema (or schema has no `properties` defined)."""
    schema = all_schemas.get(tool_name)
    if not schema:
        return False
    params = (schema.get("parameters") or {})
    props = params.get("properties") or {}
    required = params.get("required") or []
    # All required fields must be present and non-empty
    for req in required:
        if req not in args:
            return False
        v = args[req]
        if v is None or v == "":
            return False
    # Reject unknown properties (would error at MCP)
    if props:
        for k in args.keys():
            if k not in props:
                return False
    return True


# ── Real inference-time system prompts ────────────────────────────────────────
OBSERVER_SYSTEM = _OBSERVER_BASE
OPERATOR_SYSTEM = _OPERATOR_BASE


# ── Load real tool schemas (from runtime extraction) ──────────────────────────
def load_runtime_schemas(path: Path) -> dict[str, dict]:
    if not path.exists():
        raise FileNotFoundError(
            f"Schema file not found: {path}\n"
            f"Run: python training/extract_runtime_schemas.py first."
        )
    raw = json.loads(path.read_text())
    # Strip our internal _category field before using as tool schema
    schemas = {}
    for name, schema in raw.items():
        clean = {k: v for k, v in schema.items() if not k.startswith("_")}
        schemas[name] = clean
    return schemas


def role_tools(role: str, all_schemas: dict[str, dict]) -> list[dict]:
    """Return the list of tool schemas the given role agent has access to."""
    if role == "observer":
        names = OBSERVER_TOOL_NAMES
    elif role == "operator":
        names = OPERATOR_TOOL_NAMES
    else:
        raise ValueError(f"unknown role: {role}")
    # Keep only schemas that actually exist in runtime_schemas.json,
    # preserve sorted order for determinism
    return [all_schemas[n] for n in sorted(names) if n in all_schemas]


# ── Sample builders (mirror v1 logic but with real schemas + prompts) ─────────

def _build_transfer_args(row: dict) -> dict:
    """Build transfer_to_operator args matching the SDK's expected schema:
    targets is a LIST of strings (not comma-joined).
    """
    user_input = row.get("input", "")
    job_ids = re.findall(r"\b(\d{4,5})\b", user_input)
    nodes = list(row.get("source_state", {}).get("nodes", {}).keys())
    node_targets = [n for n in nodes if n in user_input]

    gt_tools = row.get("ground_truth", {}).get("tools", [])
    action_tools = [t for t in gt_tools if t in DANGEROUS_TOOLS]
    required = action_tools[0] if action_tools else "scancel"

    targets: list[str] = []
    if job_ids:
        targets = job_ids[:3]
    elif node_targets:
        targets = node_targets[:1]

    if targets:
        scope = "explicit"
    elif required in {"scontrol_reconfigure", "scontrol_shutdown", "scontrol_setdebug",
                       "sbatch", "salloc", "srun"}:
        scope = "none"
    else:
        scope = "discovery"

    args = {
        "action_request": user_input[:120],
        "required_tool": required,
        "target_scope": scope,
        "targets": targets,
    }
    return args


def build_observer_sample(row: dict, all_schemas: dict) -> dict | None:
    gt = row.get("ground_truth", {})
    tools = gt.get("tools", [])
    source_state = row.get("source_state", {})

    if gt.get("handoff"):
        return None  # handled by build_handoff_sample

    messages = [
        {"role": "system", "content": OBSERVER_SYSTEM},
        {"role": "user", "content": row["input"]},
    ]

    if not tools:
        # Ambiguous query → clarification (no tool calls)
        response = _build_final_response(row, [])
        messages.append({"role": "assistant", "content": response})
        return {"messages": messages, "tools": role_tools("observer", all_schemas)}

    tool_calls = []
    for tname in tools:
        if tname not in OBSERVER_TOOL_NAMES or tname not in all_schemas:
            continue
        args = _build_tool_args(tname, row)
        if not _validate_args_against_schema(tname, args, all_schemas):
            return None  # Drop sample rather than train an invalid call
        tool_calls.append({
            "id": f"call_{tname}_{random.randint(1000, 9999)}",
            "type": "function",
            "function": {"name": tname, "arguments": json.dumps(args)},
        })

    if not tool_calls:
        return None

    messages.append({"role": "assistant", "content": None, "tool_calls": tool_calls})

    tool_outputs = []
    for tc in tool_calls:
        out = _simulate_tool_output(tc["function"]["name"], source_state, row)
        tool_outputs.append(out)
        messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

    messages.append({"role": "assistant", "content": _build_final_response(row, tool_outputs)})
    return {"messages": messages, "tools": role_tools("observer", all_schemas)}


def build_handoff_samples(row: dict, all_schemas: dict) -> list[dict] | None:
    gt = row.get("ground_truth", {})
    tools = gt.get("tools", [])
    source_state = row.get("source_state", {})

    if not gt.get("handoff"):
        return None

    read_tools = [t for t in tools if t in OBSERVER_TOOL_NAMES and t not in DANGEROUS_TOOLS]
    action_tools = [t for t in tools if t in DANGEROUS_TOOLS and t in OPERATOR_TOOL_NAMES]

    samples: list[dict] = []

    # ── Observer half ─────────────────────────────────────────────────────────
    obs_messages = [
        {"role": "system", "content": OBSERVER_SYSTEM},
        {"role": "user", "content": row["input"]},
    ]

    if read_tools:
        pre_calls = []
        for tname in read_tools:
            if tname not in all_schemas:
                continue
            args = _build_tool_args(tname, row)
            if not _validate_args_against_schema(tname, args, all_schemas):
                return None
            pre_calls.append({
                "id": f"call_{tname}_{random.randint(1000, 9999)}",
                "type": "function",
                "function": {"name": tname, "arguments": json.dumps(args)},
            })
        if pre_calls:
            obs_messages.append({"role": "assistant", "content": None, "tool_calls": pre_calls})
            for tc in pre_calls:
                out = _simulate_tool_output(tc["function"]["name"], source_state, row)
                obs_messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

    transfer_args = _build_transfer_args(row)
    if not _validate_args_against_schema("transfer_to_operator", transfer_args, all_schemas):
        return None
    transfer_id = f"call_transfer_{random.randint(1000, 9999)}"
    obs_messages.append({
        "role": "assistant",
        "content": None,
        "tool_calls": [{
            "id": transfer_id,
            "type": "function",
            "function": {"name": "transfer_to_operator", "arguments": json.dumps(transfer_args)},
        }],
    })
    # NOTE: At inference, Observer's turn ENDS after the handoff tool call (the
    # SDK transfers control to Operator). We must NOT teach Observer to emit a
    # trailing text message — doing so trains it to keep generating after the
    # tool call instead of stopping.

    samples.append({"messages": obs_messages, "tools": role_tools("observer", all_schemas)})

    # ── Operator half ─────────────────────────────────────────────────────────
    if action_tools:
        # CRITICAL: This must mirror agent.flow.agent._operator_handoff_input_filter
        # so the model sees the SAME first user message at training as at inference.
        action_request = transfer_args.get("action_request", "")
        target_scope = transfer_args.get("target_scope", "discovery")
        required_tool = transfer_args.get("required_tool", action_tools[0])
        targets = transfer_args.get("targets", []) or []
        op_user_lines = [
            "Execute this exact cluster-state action now.",
            "Do not substitute a different action type.",
            f"Action request: {action_request}",
            f"Target scope: {target_scope}",
        ]
        if required_tool:
            op_user_lines.append(f"Required tool: {required_tool}")
        if targets:
            op_user_lines.append(f"Targets: {', '.join(targets)}")
        if target_scope == "discovery":
            op_user_lines.append(
                "IMPORTANT: Your FIRST tool call must be a read tool (squeue/sinfo/scontrol_show) to resolve concrete numeric IDs."
            )
            op_user_lines.append(
                "NEVER call the action tool with placeholder IDs like 0, ALL, or flags."
            )
            op_user_lines.append(
                f"Only after discovery, call {required_tool} with the resolved IDs."
                if required_tool
                else "Only after discovery, call the action tool with the resolved IDs."
            )
        elif required_tool:
            op_user_lines.append(f"First action tool call MUST use {required_tool}.")
        op_user = "\n".join(op_user_lines)
        op_messages: list[dict] = [
            {"role": "system", "content": OPERATOR_SYSTEM},
            {"role": "user", "content": op_user},
        ]

        # For discovery scope, Operator must first call a read tool (squeue/sinfo/
        # scontrol_show) to resolve targets, then the action tool. Mirror that.
        if target_scope == "discovery":
            # Pick a sensible read tool + args based on the action.
            # Args MUST match the real MCP signatures (squeue/sinfo).
            if required_tool in {"scancel", "scontrol_hold", "scontrol_release",
                                  "scontrol_requeue", "scontrol_suspend",
                                  "scontrol_resume_job", "scontrol_update"}:
                read_name = "squeue"
                read_args = {}
                ui_low = row.get("input", "").lower()
                if "alice" in ui_low:
                    read_args["user"] = "alice"
                elif "bob" in ui_low:
                    read_args["user"] = "bob"
                if "pending" in ui_low:
                    read_args["state"] = "PENDING"
                elif "running" in ui_low:
                    read_args["state"] = "RUNNING"
                if "gpu" in ui_low and "partition" not in read_args:
                    read_args["partition"] = "gpu"
            elif required_tool == "scontrol_node":
                read_name = "sinfo"
                read_args = {}
                if "gpu" in row.get("input", "").lower():
                    read_args["partition"] = "gpu"
            else:
                read_name = "squeue"
                read_args = {}

            if read_name in all_schemas and _validate_args_against_schema(read_name, read_args, all_schemas):
                read_id = f"call_{read_name}_{random.randint(1000, 9999)}"
                op_messages.append({
                    "role": "assistant",
                    "content": None,
                    "tool_calls": [{
                        "id": read_id,
                        "type": "function",
                        "function": {"name": read_name, "arguments": json.dumps(read_args)},
                    }],
                })
                op_messages.append({
                    "role": "tool",
                    "tool_call_id": read_id,
                    "content": _simulate_tool_output(read_name, source_state, row),
                })

        action_calls = []
        for tname in action_tools:
            if tname not in all_schemas:
                continue
            args = _build_tool_args(tname, row)
            if not _validate_args_against_schema(tname, args, all_schemas):
                # Skip the entire Operator half rather than train an invalid call.
                action_calls = []
                break
            action_calls.append({
                "id": f"call_{tname}_{random.randint(1000, 9999)}",
                "type": "function",
                "function": {"name": tname, "arguments": json.dumps(args)},
            })

        if action_calls:
            op_messages.append({"role": "assistant", "content": None, "tool_calls": action_calls})
            for tc in action_calls:
                out = _simulate_tool_output(tc["function"]["name"], source_state, row)
                op_messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

            op_messages.append({"role": "assistant", "content": _build_final_response(row, [])})
            samples.append({"messages": op_messages, "tools": role_tools("operator", all_schemas)})

    return samples or None


def build_sample(row: dict, all_schemas: dict) -> list[dict] | None:
    if row.get("ground_truth", {}).get("handoff"):
        return build_handoff_samples(row, all_schemas)
    obs = build_observer_sample(row, all_schemas)
    return [obs] if obs else None


# ── Stratified split ──────────────────────────────────────────────────────────

def stratified_split(rows: list[dict], test_ratio: float, seed: int) -> tuple[list[dict], list[dict]]:
    """Split by (category × scenario) bucket so test reflects training distribution."""
    rng = random.Random(seed)
    buckets: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for r in rows:
        key = (r.get("category", "?"), r.get("scenario", "?"))
        buckets[key].append(r)

    train, test = [], []
    for key in sorted(buckets.keys()):
        bucket = buckets[key][:]
        rng.shuffle(bucket)
        n_test = max(1, round(len(bucket) * test_ratio)) if len(bucket) >= 2 else 0
        test.extend(bucket[:n_test])
        train.extend(bucket[n_test:])

    rng.shuffle(train)
    rng.shuffle(test)
    return train, test


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="evaluation/dataset.json")
    parser.add_argument("--schemas", default="training/runtime_schemas.json")
    parser.add_argument("--out", default="training/out/agent_sft_v2.jsonl")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--split", type=float, default=0.2,
                        help="Test set ratio (default 0.2 = 80/20)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--smoke", type=int, default=0,
                        help="If >0, only build N samples (smoke test).")
    args = parser.parse_args()

    random.seed(args.seed)

    dataset_path = (ROOT / args.dataset).resolve()
    schemas_path = (ROOT / args.schemas).resolve()
    out_path = (ROOT / args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Dataset:  {dataset_path}")
    print(f"Schemas:  {schemas_path}")
    print(f"Output:   {out_path}")
    print()

    all_schemas = load_runtime_schemas(schemas_path)
    print(f"Loaded {len(all_schemas)} runtime schemas")
    obs_count = sum(1 for n in all_schemas if n in OBSERVER_TOOL_NAMES)
    op_count = sum(1 for n in all_schemas if n in OPERATOR_TOOL_NAMES)
    print(f"  Observer-allowed: {obs_count} | Operator-allowed: {op_count}")

    data = json.loads(dataset_path.read_text())
    if args.limit > 0:
        data = data[:args.limit]
    print(f"Dataset size: {len(data)}")

    # Stratified split FIRST so train/test row IDs are stable across runs
    if args.split > 0:
        train_rows, test_rows = stratified_split(data, args.split, args.seed)
        print(f"Stratified split: {len(train_rows)} train / {len(test_rows)} test")
    else:
        train_rows, test_rows = data, []

    if args.smoke > 0:
        train_rows = train_rows[: args.smoke]
        test_rows = test_rows[: max(1, args.smoke // 4)]
        print(f"[SMOKE] Reduced to {len(train_rows)} train / {len(test_rows)} test")

    # Save row-id splits so eval can pick them up
    ids_path = out_path.with_name(out_path.stem + "_ids.json")
    ids_path.write_text(json.dumps({
        "train_ids": [r.get("id") for r in train_rows],
        "test_ids": [r.get("id") for r in test_rows],
        "split_ratio": args.split,
        "seed": args.seed,
    }, indent=2))
    print(f"Row-id split saved → {ids_path}")

    def build_split(rows: list[dict]) -> list[dict]:
        out = []
        skipped = 0
        for row in rows:
            built = build_sample(row, all_schemas)
            if not built:
                skipped += 1
                continue
            for idx, sample in enumerate(built):
                sample["metadata"] = {
                    "id": row.get("id"),
                    "category": row.get("category"),
                    "scenario": row.get("scenario"),
                    "role": "operator" if idx == 1 else "observer",
                }
                out.append(sample)
        return out, skipped

    train_samples, train_skipped = build_split(train_rows)
    test_samples, test_skipped = build_split(test_rows) if test_rows else ([], 0)

    random.shuffle(train_samples)
    random.shuffle(test_samples)

    # Write
    with out_path.open("w", encoding="utf-8") as f:
        for s in train_samples:
            f.write(json.dumps(s, ensure_ascii=False) + "\n")
    print(f"\n✓ Train: {len(train_samples)} samples → {out_path} (skipped {train_skipped} rows)")

    if test_samples:
        test_out = out_path.with_name(out_path.stem + "_test.jsonl")
        with test_out.open("w", encoding="utf-8") as f:
            for s in test_samples:
                f.write(json.dumps(s, ensure_ascii=False) + "\n")
        print(f"✓ Test:  {len(test_samples)} samples → {test_out} (skipped {test_skipped} rows)")

    # Stats
    cats = Counter(s["metadata"]["category"] for s in train_samples)
    handoffs = sum(
        1 for s in train_samples if any(
            m.get("tool_calls") and any(tc["function"]["name"] == "transfer_to_operator" for tc in m["tool_calls"])
            for m in s["messages"] if isinstance(m.get("tool_calls"), list)
        )
    )
    print(f"\nTrain category dist: {dict(sorted(cats.items()))}")
    print(f"Handoff samples: {handoffs}")
    print(f"Observer-only: {len(train_samples) - handoffs}")


if __name__ == "__main__":
    main()
