#!/usr/bin/env python3
"""Build chat-style SFT data with REAL inference-time prompts and tool schemas.

Differences from build_agent_sft.py:
  1. System prompts come directly from agent/flow/instructions.py (not condensed).
  2. Tool schemas loaded from training/runtime_schemas.json (real MCP + handoff
     schemas, generated by extract_runtime_schemas.py).
  3. transfer_to_operator `targets` argument is a list of strings (matches what
     the OpenAI Agents SDK expects from _OperatorHandoffPayload).
  4. Stratified train/test split by (category × scenario) pair.

PRE-REQUISITES:
    Run extract_runtime_schemas.py FIRST (with MCP server up).

Usage (on pod):
    cd slurm-agent
    python training/extract_runtime_schemas.py            # produces runtime_schemas.json
    python training/build_agent_sft_v2.py --split 0.2     # 80/20 stratified split
    # → training/out/agent_sft_v2.jsonl + agent_sft_v2_test.jsonl
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Import REAL inference prompts (these are what the live agent uses)
from agent.flow.instructions import _OBSERVER_BASE, _OPERATOR_BASE  # type: ignore

# Reuse simulator + helper functions from v1
from training.build_agent_sft import (  # type: ignore
    _build_tool_args,
    _simulate_tool_output,
    _build_final_response,
    DANGEROUS_TOOLS,
    OBSERVER_TOOL_NAMES,
    OPERATOR_TOOL_NAMES,
)


# ── Real inference-time system prompts ────────────────────────────────────────
OBSERVER_SYSTEM = _OBSERVER_BASE
OPERATOR_SYSTEM = _OPERATOR_BASE


# ── Load real tool schemas (from runtime extraction) ──────────────────────────
def load_runtime_schemas(path: Path) -> dict[str, dict]:
    if not path.exists():
        raise FileNotFoundError(
            f"Schema file not found: {path}\n"
            f"Run: python training/extract_runtime_schemas.py first."
        )
    raw = json.loads(path.read_text())
    # Strip our internal _category field before using as tool schema
    schemas = {}
    for name, schema in raw.items():
        clean = {k: v for k, v in schema.items() if not k.startswith("_")}
        schemas[name] = clean
    return schemas


def role_tools(role: str, all_schemas: dict[str, dict]) -> list[dict]:
    """Return the list of tool schemas the given role agent has access to."""
    if role == "observer":
        names = OBSERVER_TOOL_NAMES
    elif role == "operator":
        names = OPERATOR_TOOL_NAMES
    else:
        raise ValueError(f"unknown role: {role}")
    # Keep only schemas that actually exist in runtime_schemas.json,
    # preserve sorted order for determinism
    return [all_schemas[n] for n in sorted(names) if n in all_schemas]


# ── Sample builders (mirror v1 logic but with real schemas + prompts) ─────────

def _build_transfer_args(row: dict) -> dict:
    """Build transfer_to_operator args matching the SDK's expected schema:
    targets is a LIST of strings (not comma-joined).
    """
    user_input = row.get("input", "")
    job_ids = re.findall(r"\b(\d{4,5})\b", user_input)
    nodes = list(row.get("source_state", {}).get("nodes", {}).keys())
    node_targets = [n for n in nodes if n in user_input]

    gt_tools = row.get("ground_truth", {}).get("tools", [])
    action_tools = [t for t in gt_tools if t in DANGEROUS_TOOLS]
    required = action_tools[0] if action_tools else "scancel"

    targets: list[str] = []
    if job_ids:
        targets = job_ids[:3]
    elif node_targets:
        targets = node_targets[:1]

    if targets:
        scope = "explicit"
    elif required in {"scontrol_reconfigure", "scontrol_shutdown", "scontrol_setdebug"}:
        scope = "none"
    else:
        scope = "discovery"

    args = {
        "action_request": user_input[:120],
        "required_tool": required,
        "target_scope": scope,
        "targets": targets,
    }
    return args


def build_observer_sample(row: dict, all_schemas: dict) -> dict | None:
    gt = row.get("ground_truth", {})
    tools = gt.get("tools", [])
    source_state = row.get("source_state", {})

    if gt.get("handoff"):
        return None  # handled by build_handoff_sample

    messages = [
        {"role": "system", "content": OBSERVER_SYSTEM},
        {"role": "user", "content": row["input"]},
    ]

    if not tools:
        # Ambiguous query → clarification (no tool calls)
        response = _build_final_response(row, [])
        messages.append({"role": "assistant", "content": response})
        return {"messages": messages, "tools": role_tools("observer", all_schemas)}

    tool_calls = []
    for tname in tools:
        if tname not in OBSERVER_TOOL_NAMES or tname not in all_schemas:
            continue
        args = _build_tool_args(tname, row)
        tool_calls.append({
            "id": f"call_{tname}_{random.randint(1000, 9999)}",
            "type": "function",
            "function": {"name": tname, "arguments": json.dumps(args)},
        })

    if not tool_calls:
        return None

    messages.append({"role": "assistant", "content": None, "tool_calls": tool_calls})

    tool_outputs = []
    for tc in tool_calls:
        out = _simulate_tool_output(tc["function"]["name"], source_state, row)
        tool_outputs.append(out)
        messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

    messages.append({"role": "assistant", "content": _build_final_response(row, tool_outputs)})
    return {"messages": messages, "tools": role_tools("observer", all_schemas)}


def build_handoff_samples(row: dict, all_schemas: dict) -> list[dict] | None:
    gt = row.get("ground_truth", {})
    tools = gt.get("tools", [])
    source_state = row.get("source_state", {})

    if not gt.get("handoff"):
        return None

    read_tools = [t for t in tools if t in OBSERVER_TOOL_NAMES and t not in DANGEROUS_TOOLS]
    action_tools = [t for t in tools if t in DANGEROUS_TOOLS and t in OPERATOR_TOOL_NAMES]

    samples: list[dict] = []

    # ── Observer half ─────────────────────────────────────────────────────────
    obs_messages = [
        {"role": "system", "content": OBSERVER_SYSTEM},
        {"role": "user", "content": row["input"]},
    ]

    if read_tools:
        pre_calls = []
        for tname in read_tools:
            if tname not in all_schemas:
                continue
            args = _build_tool_args(tname, row)
            pre_calls.append({
                "id": f"call_{tname}_{random.randint(1000, 9999)}",
                "type": "function",
                "function": {"name": tname, "arguments": json.dumps(args)},
            })
        if pre_calls:
            obs_messages.append({"role": "assistant", "content": None, "tool_calls": pre_calls})
            for tc in pre_calls:
                out = _simulate_tool_output(tc["function"]["name"], source_state, row)
                obs_messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

    transfer_args = _build_transfer_args(row)
    transfer_id = f"call_transfer_{random.randint(1000, 9999)}"
    obs_messages.append({
        "role": "assistant",
        "content": None,
        "tool_calls": [{
            "id": transfer_id,
            "type": "function",
            "function": {"name": "transfer_to_operator", "arguments": json.dumps(transfer_args)},
        }],
    })
    obs_messages.append({
        "role": "tool",
        "tool_call_id": transfer_id,
        "content": "Transferred to Operator agent.",
    })
    obs_messages.append({
        "role": "assistant",
        "content": "I've handed this off to the Operator for execution with confirmation.",
    })

    samples.append({"messages": obs_messages, "tools": role_tools("observer", all_schemas)})

    # ── Operator half ─────────────────────────────────────────────────────────
    if action_tools:
        op_user = (
            f"Action execution phase is complete.\n"
            f"Prepare the final user-facing summary from these results.\n"
            f"Original request: {row['input']}\n"
            f"Action: {transfer_args.get('action_request', '')}\n"
            f"Required tool: {transfer_args.get('required_tool', action_tools[0])}\n"
            f"Target scope: {transfer_args.get('target_scope', 'discovery')}\n"
            f"Targets: {transfer_args.get('targets', [])}"
        )
        op_messages: list[dict] = [
            {"role": "system", "content": OPERATOR_SYSTEM},
            {"role": "user", "content": op_user},
        ]

        action_calls = []
        for tname in action_tools:
            if tname not in all_schemas:
                continue
            args = _build_tool_args(tname, row)
            action_calls.append({
                "id": f"call_{tname}_{random.randint(1000, 9999)}",
                "type": "function",
                "function": {"name": tname, "arguments": json.dumps(args)},
            })

        if action_calls:
            op_messages.append({"role": "assistant", "content": None, "tool_calls": action_calls})
            for tc in action_calls:
                out = _simulate_tool_output(tc["function"]["name"], source_state, row)
                op_messages.append({"role": "tool", "tool_call_id": tc["id"], "content": out})

            op_messages.append({"role": "assistant", "content": _build_final_response(row, [])})
            samples.append({"messages": op_messages, "tools": role_tools("operator", all_schemas)})

    return samples or None


def build_sample(row: dict, all_schemas: dict) -> list[dict] | None:
    if row.get("ground_truth", {}).get("handoff"):
        return build_handoff_samples(row, all_schemas)
    obs = build_observer_sample(row, all_schemas)
    return [obs] if obs else None


# ── Stratified split ──────────────────────────────────────────────────────────

def stratified_split(rows: list[dict], test_ratio: float, seed: int) -> tuple[list[dict], list[dict]]:
    """Split by (category × scenario) bucket so test reflects training distribution."""
    rng = random.Random(seed)
    buckets: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for r in rows:
        key = (r.get("category", "?"), r.get("scenario", "?"))
        buckets[key].append(r)

    train, test = [], []
    for key in sorted(buckets.keys()):
        bucket = buckets[key][:]
        rng.shuffle(bucket)
        n_test = max(1, round(len(bucket) * test_ratio)) if len(bucket) >= 2 else 0
        test.extend(bucket[:n_test])
        train.extend(bucket[n_test:])

    rng.shuffle(train)
    rng.shuffle(test)
    return train, test


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="evaluation/dataset.json")
    parser.add_argument("--schemas", default="training/runtime_schemas.json")
    parser.add_argument("--out", default="training/out/agent_sft_v2.jsonl")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--split", type=float, default=0.2,
                        help="Test set ratio (default 0.2 = 80/20)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--smoke", type=int, default=0,
                        help="If >0, only build N samples (smoke test).")
    args = parser.parse_args()

    random.seed(args.seed)

    dataset_path = (ROOT / args.dataset).resolve()
    schemas_path = (ROOT / args.schemas).resolve()
    out_path = (ROOT / args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Dataset:  {dataset_path}")
    print(f"Schemas:  {schemas_path}")
    print(f"Output:   {out_path}")
    print()

    all_schemas = load_runtime_schemas(schemas_path)
    print(f"Loaded {len(all_schemas)} runtime schemas")
    obs_count = sum(1 for n in all_schemas if n in OBSERVER_TOOL_NAMES)
    op_count = sum(1 for n in all_schemas if n in OPERATOR_TOOL_NAMES)
    print(f"  Observer-allowed: {obs_count} | Operator-allowed: {op_count}")

    data = json.loads(dataset_path.read_text())
    if args.limit > 0:
        data = data[:args.limit]
    print(f"Dataset size: {len(data)}")

    # Stratified split FIRST so train/test row IDs are stable across runs
    if args.split > 0:
        train_rows, test_rows = stratified_split(data, args.split, args.seed)
        print(f"Stratified split: {len(train_rows)} train / {len(test_rows)} test")
    else:
        train_rows, test_rows = data, []

    if args.smoke > 0:
        train_rows = train_rows[: args.smoke]
        test_rows = test_rows[: max(1, args.smoke // 4)]
        print(f"[SMOKE] Reduced to {len(train_rows)} train / {len(test_rows)} test")

    # Save row-id splits so eval can pick them up
    ids_path = out_path.with_name(out_path.stem + "_ids.json")
    ids_path.write_text(json.dumps({
        "train_ids": [r.get("id") for r in train_rows],
        "test_ids": [r.get("id") for r in test_rows],
        "split_ratio": args.split,
        "seed": args.seed,
    }, indent=2))
    print(f"Row-id split saved → {ids_path}")

    def build_split(rows: list[dict]) -> list[dict]:
        out = []
        skipped = 0
        for row in rows:
            built = build_sample(row, all_schemas)
            if not built:
                skipped += 1
                continue
            for idx, sample in enumerate(built):
                sample["metadata"] = {
                    "id": row.get("id"),
                    "category": row.get("category"),
                    "scenario": row.get("scenario"),
                    "role": "operator" if idx == 1 else "observer",
                }
                out.append(sample)
        return out, skipped

    train_samples, train_skipped = build_split(train_rows)
    test_samples, test_skipped = build_split(test_rows) if test_rows else ([], 0)

    random.shuffle(train_samples)
    random.shuffle(test_samples)

    # Write
    with out_path.open("w", encoding="utf-8") as f:
        for s in train_samples:
            f.write(json.dumps(s, ensure_ascii=False) + "\n")
    print(f"\n✓ Train: {len(train_samples)} samples → {out_path} (skipped {train_skipped} rows)")

    if test_samples:
        test_out = out_path.with_name(out_path.stem + "_test.jsonl")
        with test_out.open("w", encoding="utf-8") as f:
            for s in test_samples:
                f.write(json.dumps(s, ensure_ascii=False) + "\n")
        print(f"✓ Test:  {len(test_samples)} samples → {test_out} (skipped {test_skipped} rows)")

    # Stats
    cats = Counter(s["metadata"]["category"] for s in train_samples)
    handoffs = sum(
        1 for s in train_samples if any(
            m.get("tool_calls") and any(tc["function"]["name"] == "transfer_to_operator" for tc in m["tool_calls"])
            for m in s["messages"] if isinstance(m.get("tool_calls"), list)
        )
    )
    print(f"\nTrain category dist: {dict(sorted(cats.items()))}")
    print(f"Handoff samples: {handoffs}")
    print(f"Observer-only: {len(train_samples) - handoffs}")


if __name__ == "__main__":
    main()
